using EmployeeAttendanceWithHealthDeclaration.Models;
using EmployeeAttendanceWithHealthDeclaration.Models.Domain;

namespace EmployeeAttendanceWithHealthDeclaration.Repositories
{
    public interface IEmployeeRepository
    {
        Task<IEnumerable<employee>> GetAll();
        // Returns the employee regardless of active status (active filter is enforced in
        // C#). Used by both the scan flow (ProcessScan checks active) and admin Update.
        Task<employee?> GetByEmployeeId(string employee_id);
        Task<IEnumerable<employee>> GetByProjectCode(string project_code);
        // Duplicate-enrollment lookup: returns the employee with the same name
        // (case-insensitive) + birthdate already enrolled under the provider (active or
        // not, is_deleted = 0), or null. Used by EmployeeService.Create to merge into
        // the existing account instead of rejecting.
        Task<employee?> FindDuplicate(string provider_code, string name, DateTime birthdate);
        Task<employee?> Create(employee employee);
        Task<employee?> Update(employee employee);
        Task<bool> SetInactive(string employee_id);
        // QR persistence at enrollment: stores the PNG (content = employee_id)
        // generated by QrCodeHelper into employee.qr_code_image. Called
        // after Create and after the merge-on-duplicate update (byte-identical
        // regenerate = legacy-row backfill). Best-effort: failures are logged, never
        // fail the registration.
        Task<bool> SetQrCode(string employee_id, byte[] qr_image);
        // Lightweight read for the Employees Excel export (GET
        // /Admin/GetEmployeeQrCodes): {employee_id, qr_code_image} for every row
        // that has a stored QR. Rows enrolled before the feature (NULL) are omitted.
        Task<IEnumerable<employee_qr_code>> GetQrCodes();
        // Soft delete via sp_employee_Delete: marks the given ids is_deleted = 1.
        // p_employee_ids is a CSV matched with FIND_IN_SET; single delete = one-element list.
        Task<employee_delete_result?> Delete(IEnumerable<string> employee_ids);
        Task<int> GetActiveCount();
    }
}