using EmployeeAttendanceWithHealthDeclaration.Helpers;
using EmployeeAttendanceWithHealthDeclaration.Models.Domain;
using EmployeeAttendanceWithHealthDeclaration.Repositories;
using EmployeeAttendanceWithHealthDeclaration.Tests.Infrastructure;
using Dapper;
using Xunit;

namespace EmployeeAttendanceWithHealthDeclaration.Tests.Repositories
{
    [Collection("database")]
    [Trait("Category", "Integration")]
    public class EmployeeRepositoryIntegrationTests
    {
        private readonly DatabaseCollectionFixture _fixture;

        public EmployeeRepositoryIntegrationTests(DatabaseCollectionFixture fixture)
        {
            _fixture = fixture;
        }

        private static employee NewEmployee(string name = "TST New Employee") => new()
        {
            name = name,
            gender = "Male",
            birthdate = DateTime.Today.AddYears(-28),
            contact_number = "09170000000",
            address = "TST Address",
            provider_code = IntegrationSeed.ProviderCode,
            active = 1,
            assignments = new List<employee_project_assignment>()
        };

        [Fact]
        public async Task Create_generates_provider_scoped_id_and_hydrates_assignment_aggregates()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateProjectAsync(connection);
            var repo = new EmployeeRepository(connection);
            var submitted = NewEmployee();
            submitted.assignments!.Add(new employee_project_assignment
            {
                project_code = IntegrationSeed.ProjectCode,
                position = "Welder"
            });

            var created = await repo.Create(submitted);

            Assert.NotNull(created);
            // {provider_code}-NNNNNN, generated by the SP (first row for this fresh provider).
            Assert.Matches("^TST-\\d{6}$", created!.employee_id);
            Assert.Equal("TST", created.provider_code);
            Assert.Equal("TST Provider Co", created.provider_name);
            Assert.Equal(IntegrationSeed.ProjectCode, created.project_codes);
            Assert.Equal("Welder", created.positions);
            Assert.Contains(IntegrationSeed.ProjectCode, created.project_positions);
            Assert.Equal(1, created.active_project_count);
        }

        // PIN: assignments to nonexistent or wrong-provider projects are silently
        // dropped by the JSON_TABLE INNER JOIN — no error surfaces to the caller.
        [Fact]
        public async Task Create_silently_drops_wrong_provider_assignments()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateProviderAsync(connection, provider_code: "TSTP-OTHER");
            await IntegrationSeed.CreateProjectAsync(connection, project_code: "TSTOP-26-001", provider_code: "TSTP-OTHER");
            var repo = new EmployeeRepository(connection);
            var submitted = NewEmployee();
            submitted.assignments!.Add(new employee_project_assignment
            {
                project_code = "TSTOP-26-001",   // belongs to a different provider
                position = "Welder"
            });

            var created = await repo.Create(submitted);

            Assert.NotNull(created);
            Assert.True(string.IsNullOrEmpty(created!.project_codes));   // zero rows -> NULL/empty GROUP_CONCAT
            Assert.Equal(0, created.active_project_count);
            var junctionRows = await connection.ExecuteScalarAsync<int>(
                "SELECT COUNT(*) FROM employee_project WHERE employee_id = @id",
                new { id = created.employee_id });
            Assert.Equal(0, junctionRows);   // PIN: silently dropped, not rejected
        }

        [Fact]
        public async Task GetByEmployeeId_missing_returns_null()
        {
            await using var connection = _fixture.CreateConnection();
            var repo = new EmployeeRepository(connection);

            Assert.Null(await repo.GetByEmployeeId("TST-999999"));
        }

        [Fact]
        public async Task GetByEmployeeId_hides_soft_deleted_employees()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000021", is_deleted: 1);
            var repo = new EmployeeRepository(connection);

            Assert.Null(await repo.GetByEmployeeId("TST-000021"));
        }

        [Fact]
        public async Task GetAll_renders_project_details_as_name_position_area()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateProjectAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: IntegrationSeed.EmployeeId);
            await IntegrationSeed.AssignProjectAsync(connection, IntegrationSeed.EmployeeId, IntegrationSeed.ProjectCode, "Welder");
            var repo = new EmployeeRepository(connection);

            var all = await repo.GetAll();

            var row = Assert.Single(all, c => c.employee_id == IntegrationSeed.EmployeeId);
            // v3.1.1.0 combined column format: "Name (Position - Area)".
            Assert.Equal("TST Project (Welder - TST Area)", row.project_details);
        }

        [Fact]
        public async Task Update_rewrites_the_assignment_rows()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateProjectAsync(connection, project_code: "TST-26-801");
            await IntegrationSeed.CreateProjectAsync(connection, project_code: "TST-26-802");
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000022");
            await IntegrationSeed.AssignProjectAsync(connection, "TST-000022", "TST-26-801");
            var repo = new EmployeeRepository(connection);
            var existing = await repo.GetByEmployeeId("TST-000022");

            existing!.assignments = new List<employee_project_assignment>
            {
                new() { project_code = "TST-26-802", position = "Supervisor" }
            };
            existing.name = "TST Renamed";
            var updated = await repo.Update(existing);

            var fetched = await repo.GetByEmployeeId("TST-000022");
            Assert.Equal("TST Renamed", fetched!.name);
            Assert.Equal("TST-26-802", fetched.project_codes);
            Assert.Equal("Supervisor", fetched.positions);
            var oldMapping = await connection.ExecuteScalarAsync<int>(
                "SELECT COUNT(*) FROM employee_project WHERE employee_id = 'TST-000022' AND project_code = 'TST-26-801'");
            Assert.Equal(0, oldMapping);   // delete-all + re-insert semantics
        }

        [Fact]
        public async Task FindDuplicate_matches_trimmed_cased_insensitive_name_and_birthdate()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            var birthdate = new DateTime(1995, 6, 15);
            await IntegrationSeed.CreateEmployeeAsync(
                connection, employee_id: "TST-000023", name: "Juan Dela Cruz", birthdate: birthdate);
            var repo = new EmployeeRepository(connection);

            var duplicate = await repo.FindDuplicate("TST", "  JUAN DELA CRUZ  ", birthdate);

            Assert.NotNull(duplicate);
            Assert.Equal("TST-000023", duplicate!.employee_id);
        }

        [Fact]
        public async Task FindDuplicate_is_scoped_by_provider_and_birthdate()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateProviderAsync(connection, provider_code: "TSTP-OTHER");
            var birthdate = new DateTime(1995, 6, 15);
            await IntegrationSeed.CreateEmployeeAsync(
                connection, employee_id: "TST-000024", name: "Maria Santos", birthdate: birthdate);
            var repo = new EmployeeRepository(connection);

            // Same person under a different provider -> NOT a duplicate.
            Assert.Null(await repo.FindDuplicate("TSTP-OTHER", "Maria Santos", birthdate));
            // Same name+provider but different birthdate -> NOT a duplicate.
            Assert.Null(await repo.FindDuplicate("TST", "Maria Santos", birthdate.AddDays(1)));
        }

        [Fact]
        public async Task FindDuplicate_excludes_soft_deleted_employees()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(
                connection, employee_id: "TST-000025", name: "Deleted Person", is_deleted: 1);
            var repo = new EmployeeRepository(connection);

            Assert.Null(await repo.FindDuplicate("TST", "Deleted Person", DateTime.Today.AddYears(-30)));
        }

        [Fact]
        public async Task Delete_soft_deletes_by_csv_and_keeps_time_logs()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000026");
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000027");
            var logId = await IntegrationSeed.CreateTimeLogAsync(connection, "TST-000026");
            var repo = new EmployeeRepository(connection);

            var result = await repo.Delete(new[] { "TST-000026", "TST-000027" });

            Assert.NotNull(result);
            Assert.True(result!.success);
            Assert.Equal(2, result.deleted_count);
            var flags = await connection.QueryAsync<(string employee_id, int is_deleted)>(
                "SELECT employee_id, is_deleted FROM employee WHERE employee_id IN ('TST-000026','TST-000027')");
            Assert.All(flags, f => Assert.Equal(1, f.is_deleted));
            // Attendance history is never touched by a employee soft delete.
            var logExists = await connection.ExecuteScalarAsync<int>(
                "SELECT COUNT(*) FROM time_logs WHERE attendance_id = @id", new { id = logId });
            Assert.Equal(1, logExists);
        }

        [Fact]
        public async Task Delete_second_time_counts_nothing()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000028");
            var repo = new EmployeeRepository(connection);
            await repo.Delete(new[] { "TST-000028" });

            var second = await repo.Delete(new[] { "TST-000028" });

            Assert.Equal(0, second!.deleted_count);   // already-deleted rows excluded
        }

        [Fact]
        public async Task SetQrCode_stores_the_blob_and_GetQrCodes_returns_it()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000029");
            var repo = new EmployeeRepository(connection);
            var png = QrCodeHelper.GeneratePng("TST-000029");

            var stored = await repo.SetQrCode("TST-000029", png);
            var fetched = (await repo.GetQrCodes()).ToList();

            Assert.True(stored);
            var row = Assert.Single(fetched, q => q.employee_id == "TST-000029");
            Assert.True(png.SequenceEqual(row.qr_code_image), "QR blob must round-trip byte-identical");
        }

        [Fact]
        public async Task SetInactive_deactivates_the_employee()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000030");
            var repo = new EmployeeRepository(connection);

            var result = await repo.SetInactive("TST-000030");

            var active = await connection.ExecuteScalarAsync<int>(
                "SELECT active FROM employee WHERE employee_id = 'TST-000030'");
            Assert.Equal(0, active);
            Assert.True(result);
        }

        [Fact]
        public async Task GetActiveCount_counts_only_active_undeleted_employees()
        {
            await using var connection = _fixture.CreateConnection();
            await IntegrationSeed.CreateProviderAsync(connection);
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000031");            // active
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000032", active: 0); // inactive
            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000033", is_deleted: 1); // deleted
            var repo = new EmployeeRepository(connection);
            var before = await repo.GetActiveCount();

            await IntegrationSeed.CreateEmployeeAsync(connection, employee_id: "TST-000034");            // +1 active

            var after = await repo.GetActiveCount();
            Assert.Equal(before + 1, after);   // delta-based assertion
        }
    }
}
