using ContractorAttendanceWithHealthDeclaration.Helpers;
using ContractorAttendanceWithHealthDeclaration.Models;
using ContractorAttendanceWithHealthDeclaration.Models.Domain;
using ContractorAttendanceWithHealthDeclaration.Repositories;
using System.Text.Json;

namespace ContractorAttendanceWithHealthDeclaration.Services
{
    public class ContractorService : IContractorService
    {
        private readonly IContractorEmployeeRepository _contractorRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IProviderRepository _providerRepository;
        private readonly IAuditLogService _auditLogService;
        private readonly ILogger<ContractorService> _logger;

        public ContractorService(
            IContractorEmployeeRepository contractorRepository,
            IProjectRepository projectRepository,
            IProviderRepository providerRepository,
            IAuditLogService auditLogService,
            ILogger<ContractorService> logger)
        {
            _contractorRepository = contractorRepository;
            _projectRepository = projectRepository;
            _providerRepository = providerRepository;
            _auditLogService = auditLogService;
            _logger = logger;
        }

        public async Task<Response<contractor_employee>> GetByEmployeeId(string employee_id)
        {
            try
            {
                var contractor = await _contractorRepository.GetByEmployeeId(employee_id);
                if (contractor == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor not found",
                        Data = null
                    };
                }

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor retrieved successfully",
                    Data = contractor
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting contractor: {EmployeeId}", employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error retrieving contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<IEnumerable<contractor_employee>>> GetAll()
        {
            try
            {
                var contractors = await _contractorRepository.GetAll();
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = true,
                    Message = "Contractors retrieved successfully",
                    Data = contractors
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting all contractors");
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = false,
                    Message = "Error retrieving contractors",
                    Data = null
                };
            }
        }

        public async Task<Response<contractor_employee>> Create(contractor_employee employee, string admin_employee_id, bool log_audit = true)
        {
            try
            {
                // Validate required fields + birthdate (DOLE 18+). employee_id is NOT required
                // on create - it is auto-generated by the stored procedure as {project_code}-NNNN.
                var validationError = ValidationHelper.ValidateContractorEmployee(employee);
                if (validationError != null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = validationError,
                        Data = null
                    };
                }

                // Validate project exists
                var project = await _projectRepository.GetByProjectCode(employee.project_code);
                if (project == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Project not found",
                        Data = null
                    };
                }

                // Validate provider exists
                var provider = await _providerRepository.GetByProviderCode(employee.provider_code);
                if (provider == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Provider not found",
                        Data = null
                    };
                }

                // Duplicate guard: a contractor with the same name (case-insensitive) and
                // birthdate already enrolled in this project (active or inactive) cannot be
                // added again. BulkCreate reuses Create() per row, so this also catches
                // intra-batch duplicates once earlier rows are committed.
                if (employee.birthdate.HasValue)
                {
                    var isDuplicate = await _contractorRepository.ExistsByDetails(
                        employee.project_code, employee.name, employee.birthdate.Value);
                    if (isDuplicate)
                    {
                        return new Response<contractor_employee>
                        {
                            Success = false,
                            Message = "A contractor with this name and birthdate is already enrolled in this project.",
                            Data = null
                        };
                    }
                }

                // employee_id is auto-generated by the stored procedure ({project_code}-NNNN)
                var result = await _contractorRepository.Create(employee);
                if (result == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Error creating contractor",
                        Data = null
                    };
                }

                _logger.LogInformation("Contractor created: {EmployeeId}", result.employee_id);

                if (log_audit)
                {
                    await _auditLogService.Log("contractor", "create", result.employee_id, null, result, admin_employee_id);
                }

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor created successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating contractor: {EmployeeId}", employee.employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error creating contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<contractor_employee>> Update(contractor_employee employee, string admin_employee_id)
        {
            try
            {
                // Validate required fields. On update the employee_id is also required (it is the key).
                if (employee == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor data is required",
                        Data = null
                    };
                }

                if (string.IsNullOrWhiteSpace(employee.employee_id))
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Employee ID is required",
                        Data = null
                    };
                }

                var validationError = ValidationHelper.ValidateContractorEmployee(employee);
                if (validationError != null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = validationError,
                        Data = null
                    };
                }

                // Validate contractor exists (include inactive so they can be reactivated)
                var existing = await _contractorRepository.GetByEmployeeId(employee.employee_id);
                if (existing == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor not found",
                        Data = null
                    };
                }

                // Validate project exists
                var project = await _projectRepository.GetByProjectCode(employee.project_code);
                if (project == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Project not found",
                        Data = null
                    };
                }

                // Validate provider exists
                var provider = await _providerRepository.GetByProviderCode(employee.provider_code);
                if (provider == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Provider not found",
                        Data = null
                    };
                }

                var result = await _contractorRepository.Update(employee);
                _logger.LogInformation("Contractor updated: {EmployeeId}", employee.employee_id);

                await _auditLogService.Log("contractor", "update", employee.employee_id, existing, result, admin_employee_id);

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor updated successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating contractor: {EmployeeId}", employee.employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error updating contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<bool>> SetInactive(string employee_id)
        {
            try
            {
                var result = await _contractorRepository.SetInactive(employee_id);
                _logger.LogInformation("Contractor set inactive: {EmployeeId}", employee_id);

                return new Response<bool>
                {
                    Success = true,
                    Message = "Contractor set inactive successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error setting contractor inactive: {EmployeeId}", employee_id);
                return new Response<bool>
                {
                    Success = false,
                    Message = "Error setting contractor inactive",
                    Data = false
                };
            }
        }

        public async Task<Response<int>> Delete(List<string> employee_ids, string admin_employee_id)
        {
            try
            {
                // Manual validation (request DTOs carry no data annotations by convention).
                if (employee_ids == null || employee_ids.Count == 0)
                {
                    return new Response<int> { Success = false, Message = "No contractor IDs were provided.", Data = 0 };
                }

                // Normalize: trim, drop blanks, reject comma-bearing ids (the SP
                // receives the ids as a CSV matched with FIND_IN_SET), de-duplicate.
                var ids = employee_ids
                    .Where(id => !string.IsNullOrWhiteSpace(id))
                    .Select(id => id.Trim())
                    .Where(id => !id.Contains(','))
                    .Distinct(StringComparer.Ordinal)
                    .ToList();

                if (ids.Count == 0)
                {
                    return new Response<int> { Success = false, Message = "No valid contractor IDs were provided.", Data = 0 };
                }

                // Fetch existing (not-yet-deleted) contractors: audit trail data_from +
                // skip ids that are unknown or already deleted (the lookup SP filters is_deleted = 0).
                var existing = new List<contractor_employee>();
                foreach (var id in ids)
                {
                    var contractor = await _contractorRepository.GetByEmployeeId(id);
                    if (contractor != null)
                    {
                        existing.Add(contractor);
                    }
                }

                if (existing.Count == 0)
                {
                    return new Response<int> { Success = false, Message = "No contractors were found to delete (they may have already been deleted).", Data = 0 };
                }

                var result = await _contractorRepository.Delete(existing.Select(c => c.employee_id));
                var deletedCount = result?.deleted_count ?? 0;

                _logger.LogInformation("Admin {AdminId} soft-deleted {DeletedCount} contractor(s)", admin_employee_id, deletedCount);

                // One audit entry for the call (mirrors timelog/project delete: previous
                // state in data_from, null data_to). audit_log.reference_id is VARCHAR(100),
                // so bulk deletes use a count summary instead of the full id CSV.
                var referenceId = existing.Count == 1 ? existing[0].employee_id : $"{existing.Count} contractors";
                await _auditLogService.Log("contractor", "delete", referenceId, existing, null, admin_employee_id);

                var skipped = ids.Count - deletedCount;
                return new Response<int>
                {
                    Success = deletedCount > 0,
                    Message = $"Deleted {deletedCount} contractor(s) successfully"
                        + (skipped > 0 ? $" ({skipped} skipped - not found or already deleted)" : string.Empty),
                    Data = deletedCount
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deleting contractors ({Count} ids)", employee_ids?.Count ?? 0);
                return new Response<int> { Success = false, Message = "Error deleting contractors", Data = 0 };
            }
        }

        public async Task<Response<IEnumerable<contractor_employee>>> GetByProjectCode(string project_code)
        {
            try
            {
                var contractors = await _contractorRepository.GetByProjectCode(project_code);
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = true,
                    Message = "Contractors retrieved successfully",
                    Data = contractors
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting contractors for project: {ProjectCode}", project_code);
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = false,
                    Message = "Error retrieving contractors"
                };
            }
        }

        public async Task<Response<int>> GetActiveCount()
        {
            try
            {
                var count = await _contractorRepository.GetActiveCount();
                return new Response<int>
                {
                    Success = true,
                    Message = "Active contractors count retrieved successfully",
                    Data = count
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting active contractors count");
                return new Response<int>
                {
                    Success = false,
                    Message = "Error retrieving active contractors count",
                    Data = 0
                };
            }
        }

        /// <summary>
        /// Project-status cascade: set every active contractor under the project to
        /// In-Active. Each deactivation is audit-logged as
        /// contractor/deactivate_by_project so a later project re-activation can
        /// restore exactly these contractors. Mirrors the nightly expiry sweep
        /// (sp_project_DeactivateExpired) for manual admin deactivation.
        /// </summary>
        public async Task<Response<int>> CascadeDeactivateByProject(string project_code, string admin_employee_id)
        {
            try
            {
                // GetByProjectCode returns active contractors only - exactly the target set.
                var contractors = await _contractorRepository.GetByProjectCode(project_code);
                var deactivated = 0;

                foreach (var contractor in contractors)
                {
                    var previous = CloneContractor(contractor);
                    contractor.active = 0;
                    var updated = await _contractorRepository.Update(contractor);

                    if (updated != null)
                    {
                        deactivated++;
                        await _auditLogService.Log(
                            "contractor", "deactivate_by_project", contractor.employee_id,
                            previous, updated, admin_employee_id);
                    }
                }

                _logger.LogInformation("Project cascade set {Count} contractor(s) inactive: {ProjectCode}",
                    deactivated, project_code);

                return new Response<int>
                {
                    Success = true,
                    Message = $"{deactivated} contractor(s) deactivated",
                    Data = deactivated
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error cascading contractor deactivation for project: {ProjectCode}", project_code);
                return new Response<int>
                {
                    Success = false,
                    Message = "Error deactivating contractors",
                    Data = 0
                };
            }
        }

        /// <summary>
        /// Restores contractors that were deactivated BY A PROJECT CASCADE for this
        /// project; the audit log is the source of truth. A contractor is restored
        /// only when it is currently In-Active, still belongs to this project, and
        /// its latest active 1-&gt;0 audit transition is a deactivate_by_project entry
        /// for this project. Contractors deactivated individually by an admin (their
        /// latest transition is a manual contractor/update) stay In-Active.
        /// </summary>
        public async Task<Response<int>> CascadeReactivateByProject(string project_code, string admin_employee_id)
        {
            try
            {
                // Candidates come from the audit trail, not GetByProjectCode (that
                // stored procedure returns active contractors only).
                var cascadeEntries = await _auditLogService.GetByEntity("contractor", "deactivate_by_project");
                var updateEntries = await _auditLogService.GetByEntity("contractor", "update");

                // employee_id -> latest audit entry that flipped active from 1 to 0
                var latestDeactivation = new Dictionary<string, audit_log>();
                TrackLatestDeactivation(cascadeEntries, latestDeactivation);
                TrackLatestDeactivation(updateEntries, latestDeactivation);

                var reactivated = 0;

                foreach (var (employee_id, entry) in latestDeactivation)
                {
                    if (!string.Equals(entry.action, "deactivate_by_project", StringComparison.Ordinal))
                    {
                        // Latest deactivation was a manual admin edit - leave In-Active.
                        continue;
                    }

                    if (!TryGetJsonString(entry.data_to, "project_code", out var cascadeProjectCode) ||
                        !string.Equals(cascadeProjectCode, project_code, StringComparison.OrdinalIgnoreCase))
                    {
                        // The cascade belonged to a different project.
                        continue;
                    }

                    var contractor = await _contractorRepository.GetByEmployeeId(employee_id);
                    if (contractor == null || contractor.active != 0 ||
                        !string.Equals(contractor.project_code, project_code, StringComparison.OrdinalIgnoreCase))
                    {
                        // Deleted, already active, or moved to another project.
                        continue;
                    }

                    var previous = CloneContractor(contractor);
                    contractor.active = 1;
                    var updated = await _contractorRepository.Update(contractor);

                    if (updated != null)
                    {
                        reactivated++;
                        await _auditLogService.Log(
                            "contractor", "reactivate_by_project", contractor.employee_id,
                            previous, updated, admin_employee_id);
                    }
                }

                _logger.LogInformation("Project re-activation restored {Count} contractor(s): {ProjectCode}",
                    reactivated, project_code);

                return new Response<int>
                {
                    Success = true,
                    Message = $"{reactivated} contractor(s) re-activated",
                    Data = reactivated
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error restoring cascade-deactivated contractors for project: {ProjectCode}", project_code);
                return new Response<int>
                {
                    Success = false,
                    Message = "Error re-activating contractors",
                    Data = 0
                };
            }
        }

        /// <summary>
        /// Bulk-import contractors for a single provider/project from a parsed file.
        /// Provider/project are validated once (and must belong together); each row is
        /// then inserted via Create() so it reuses the same field + DOLE 18+ validation
        /// and the {project_code}-NNNN auto employee_id generation. Valid rows insert;
        /// invalid rows are collected with row number + reason. One audit_log batch row
        /// is written regardless of partial failures.
        /// </summary>
        public async Task<Response<bulk_enrollment_result>> BulkCreate(bulk_enrollment_request request, string admin_employee_id)
        {
            var result = new bulk_enrollment_result
            {
                provider_code = request?.provider_code,
                project_code = request?.project_code,
                file_name = request?.file_name
            };

            try
            {
                if (request == null || request.contractors == null || request.contractors.Count == 0)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "No contractor rows were provided for import.",
                        Data = result
                    };
                }

                result.total = request.contractors.Count;

                // Fail fast: the modal's provider/project must be valid and belong together.
                if (string.IsNullOrWhiteSpace(request.provider_code) || string.IsNullOrWhiteSpace(request.project_code))
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Provider and Project are required.",
                        Data = result
                    };
                }

                var project = await _projectRepository.GetByProjectCode(request.project_code);
                if (project == null)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Selected project was not found.",
                        Data = result
                    };
                }

                if (!string.Equals(project.provider_code, request.provider_code, StringComparison.OrdinalIgnoreCase))
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "The selected project does not belong to the selected provider.",
                        Data = result
                    };
                }

                var provider = await _providerRepository.GetByProviderCode(request.provider_code);
                if (provider == null)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Selected provider was not found.",
                        Data = result
                    };
                }

                // Insert each row. Create() enforces required fields, DOLE 18+ birthdate,
                // and provider/project existence; gender is checked here because Create()
                // does not validate it.
                foreach (var row in request.contractors)
                {
                    var normalizedGender = (row.gender ?? string.Empty).Trim();
                    if (!string.Equals(normalizedGender, "Male", StringComparison.OrdinalIgnoreCase) &&
                        !string.Equals(normalizedGender, "Female", StringComparison.OrdinalIgnoreCase))
                    {
                        result.error_count++;
                        result.errors.Add(new bulk_enrollment_error
                        {
                            row = row.row_number,
                            name = row.name,
                            message = "Gender must be Male or Female."
                        });
                        continue;
                    }

                    var employee = new contractor_employee
                    {
                        name = row.name,
                        gender = normalizedGender,
                        birthdate = row.birthdate,
                        contact_number = row.contact_number,
                        address = row.address,
                        area_of_destination = row.area_of_destination,
                        position = row.position,
                        provider_code = request.provider_code,
                        project_code = request.project_code,
                        active = 1
                    };

                    // Per-row audit is suppressed here; BulkCreate writes one summary
                    // bulk_enrollment audit entry for the whole batch (see below).
                    var created = await Create(employee, admin_employee_id, log_audit: false);
                    if (created.Success && created.Data != null)
                    {
                        result.success_count++;
                        result.enrolled_employee_ids.Add(created.Data.employee_id);
                    }
                    else
                    {
                        result.error_count++;
                        result.errors.Add(new bulk_enrollment_error
                        {
                            row = row.row_number,
                            name = row.name,
                            message = created.Message ?? "Could not enroll this contractor."
                        });
                    }
                }

                // Record the batch in the reusable audit log (best-effort: never fail the
                // import if logging itself fails).
                var logResponse = await _auditLogService.Log(
                    "bulk_enrollment",
                    "bulk_create",
                    request.project_code,
                    null,
                    result,
                    admin_employee_id);

                if (logResponse.Success && logResponse.Data != null)
                {
                    result.log_id = logResponse.Data.log_id;
                }

                _logger.LogInformation(
                    "Bulk enrollment complete: {Success} succeeded, {Errors} failed (project {ProjectCode}, admin {Admin})",
                    result.success_count, result.error_count, request.project_code, admin_employee_id);

                return new Response<bulk_enrollment_result>
                {
                    Success = true,
                    Message = $"Enrolled {result.success_count} of {result.total} contractor(s); {result.error_count} failed.",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error during bulk enrollment (project {ProjectCode})", request?.project_code);
                return new Response<bulk_enrollment_result>
                {
                    Success = false,
                    Message = "An error occurred during bulk enrollment.",
                    Data = result
                };
            }
        }

        /// <summary>
        /// Shallow copy so audit data_from captures the pre-change state before the
        /// cascade methods mutate the entity in place.
        /// </summary>
        private static contractor_employee CloneContractor(contractor_employee source) => new()
        {
            employee_id = source.employee_id,
            name = source.name,
            gender = source.gender,
            birthdate = source.birthdate,
            contact_number = source.contact_number,
            address = source.address,
            area_of_destination = source.area_of_destination,
            project_code = source.project_code,
            provider_code = source.provider_code,
            provider_name = source.provider_name,
            project_name = source.project_name,
            position = source.position,
            active = source.active,
            create_at = source.create_at,
            update_at = source.update_at
        };

        /// <summary>
        /// Folds audit entries into latestDeactivation, keeping the highest log_id
        /// per employee for entries that flipped active from 1 to 0.
        /// </summary>
        private static void TrackLatestDeactivation(
            Response<IEnumerable<audit_log>>? response,
            Dictionary<string, audit_log> latestDeactivation)
        {
            if (response?.Success != true || response.Data == null)
            {
                return;
            }

            foreach (var entry in response.Data)
            {
                if (string.IsNullOrWhiteSpace(entry.reference_id) || !IsActiveDeactivation(entry))
                {
                    continue;
                }

                if (latestDeactivation.TryGetValue(entry.reference_id, out var current) && current.log_id >= entry.log_id)
                {
                    continue;
                }

                latestDeactivation[entry.reference_id] = entry;
            }
        }

        /// <summary>
        /// True when the entry flipped active from 1 (data_from) to 0 (data_to).
        /// Handles both C#-serialized (indented) and MySQL JSON_OBJECT (compact)
        /// payloads; edits that leave active unchanged are not transitions.
        /// </summary>
        private static bool IsActiveDeactivation(audit_log entry)
        {
            return TryGetJsonInt(entry.data_from, "active", out var fromActive) && fromActive == 1
                && TryGetJsonInt(entry.data_to, "active", out var toActive) && toActive == 0;
        }

        private static bool TryGetJsonInt(string? json, string property, out int value)
        {
            value = 0;
            if (string.IsNullOrWhiteSpace(json))
            {
                return false;
            }

            try
            {
                using var document = JsonDocument.Parse(json);
                if (document.RootElement.TryGetProperty(property, out var element)
                    && element.ValueKind == JsonValueKind.Number)
                {
                    return element.TryGetInt32(out value);
                }
                return false;
            }
            catch (JsonException)
            {
                return false;
            }
        }

        private static bool TryGetJsonString(string? json, string property, out string value)
        {
            value = string.Empty;
            if (string.IsNullOrWhiteSpace(json))
            {
                return false;
            }

            try
            {
                using var document = JsonDocument.Parse(json);
                if (document.RootElement.TryGetProperty(property, out var element)
                    && element.ValueKind == JsonValueKind.String)
                {
                    value = element.GetString() ?? string.Empty;
                    return value != string.Empty;
                }
                return false;
            }
            catch (JsonException)
            {
                return false;
            }
        }
    }
}