using ContractorAttendanceWithHealthDeclaration.Helpers;
using ContractorAttendanceWithHealthDeclaration.Models;
using ContractorAttendanceWithHealthDeclaration.Models.Domain;
using ContractorAttendanceWithHealthDeclaration.Repositories;

namespace ContractorAttendanceWithHealthDeclaration.Services
{
    public class ContractorService : IContractorService
    {
        private readonly IContractorEmployeeRepository _contractorRepository;
        private readonly IProjectRepository _projectRepository;
        private readonly IProviderRepository _providerRepository;
        private readonly IAuditLogService _auditLogService;
        private readonly ILogger<ContractorService> _logger;

        public ContractorService(
            IContractorEmployeeRepository contractorRepository,
            IProjectRepository projectRepository,
            IProviderRepository providerRepository,
            IAuditLogService auditLogService,
            ILogger<ContractorService> logger)
        {
            _contractorRepository = contractorRepository;
            _projectRepository = projectRepository;
            _providerRepository = providerRepository;
            _auditLogService = auditLogService;
            _logger = logger;
        }

        public async Task<Response<contractor_employee>> GetByEmployeeId(string employee_id)
        {
            try
            {
                var contractor = await _contractorRepository.GetByEmployeeId(employee_id);
                if (contractor == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor not found",
                        Data = null
                    };
                }

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor retrieved successfully",
                    Data = contractor
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting contractor: {EmployeeId}", employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error retrieving contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<IEnumerable<contractor_employee>>> GetAll()
        {
            try
            {
                var contractors = await _contractorRepository.GetAll();
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = true,
                    Message = "Contractors retrieved successfully",
                    Data = contractors
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting all contractors");
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = false,
                    Message = "Error retrieving contractors",
                    Data = null
                };
            }
        }

        public async Task<Response<contractor_employee>> Create(contractor_employee employee)
        {
            try
            {
                // Validate required fields + birthdate (DOLE 18+). employee_id is NOT required
                // on create - it is auto-generated by the stored procedure as {project_code}-NNNN.
                var validationError = ValidationHelper.ValidateContractorEmployee(employee);
                if (validationError != null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = validationError,
                        Data = null
                    };
                }

                // Validate project exists
                var project = await _projectRepository.GetByProjectCode(employee.project_code);
                if (project == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Project not found",
                        Data = null
                    };
                }

                // Validate provider exists
                var provider = await _providerRepository.GetByProviderCode(employee.provider_code);
                if (provider == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Provider not found",
                        Data = null
                    };
                }

                // Duplicate guard: a contractor with the same name (case-insensitive) and
                // birthdate already enrolled in this project (active or inactive) cannot be
                // added again. BulkCreate reuses Create() per row, so this also catches
                // intra-batch duplicates once earlier rows are committed.
                if (employee.birthdate.HasValue)
                {
                    var isDuplicate = await _contractorRepository.ExistsByDetails(
                        employee.project_code, employee.name, employee.birthdate.Value);
                    if (isDuplicate)
                    {
                        return new Response<contractor_employee>
                        {
                            Success = false,
                            Message = "A contractor with this name and birthdate is already enrolled in this project.",
                            Data = null
                        };
                    }
                }

                // employee_id is auto-generated by the stored procedure ({project_code}-NNNN)
                var result = await _contractorRepository.Create(employee);
                if (result == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Error creating contractor",
                        Data = null
                    };
                }

                _logger.LogInformation("Contractor created: {EmployeeId}", result.employee_id);

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor created successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error creating contractor: {EmployeeId}", employee.employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error creating contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<contractor_employee>> Update(contractor_employee employee)
        {
            try
            {
                // Validate required fields. On update the employee_id is also required (it is the key).
                if (employee == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor data is required",
                        Data = null
                    };
                }

                if (string.IsNullOrWhiteSpace(employee.employee_id))
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Employee ID is required",
                        Data = null
                    };
                }

                var validationError = ValidationHelper.ValidateContractorEmployee(employee);
                if (validationError != null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = validationError,
                        Data = null
                    };
                }

                // Validate contractor exists (include inactive so they can be reactivated)
                var existing = await _contractorRepository.GetByEmployeeId(employee.employee_id);
                if (existing == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Contractor not found",
                        Data = null
                    };
                }

                // Validate project exists
                var project = await _projectRepository.GetByProjectCode(employee.project_code);
                if (project == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Project not found",
                        Data = null
                    };
                }

                // Validate provider exists
                var provider = await _providerRepository.GetByProviderCode(employee.provider_code);
                if (provider == null)
                {
                    return new Response<contractor_employee>
                    {
                        Success = false,
                        Message = "Provider not found",
                        Data = null
                    };
                }

                var result = await _contractorRepository.Update(employee);
                _logger.LogInformation("Contractor updated: {EmployeeId}", employee.employee_id);

                return new Response<contractor_employee>
                {
                    Success = true,
                    Message = "Contractor updated successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error updating contractor: {EmployeeId}", employee.employee_id);
                return new Response<contractor_employee>
                {
                    Success = false,
                    Message = "Error updating contractor",
                    Data = null
                };
            }
        }

        public async Task<Response<bool>> SetInactive(string employee_id)
        {
            try
            {
                var result = await _contractorRepository.SetInactive(employee_id);
                _logger.LogInformation("Contractor set inactive: {EmployeeId}", employee_id);

                return new Response<bool>
                {
                    Success = true,
                    Message = "Contractor set inactive successfully",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error setting contractor inactive: {EmployeeId}", employee_id);
                return new Response<bool>
                {
                    Success = false,
                    Message = "Error setting contractor inactive",
                    Data = false
                };
            }
        }

        public async Task<Response<IEnumerable<contractor_employee>>> GetByProjectCode(string project_code)
        {
            try
            {
                var contractors = await _contractorRepository.GetByProjectCode(project_code);
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = true,
                    Message = "Contractors retrieved successfully",
                    Data = contractors
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting contractors for project: {ProjectCode}", project_code);
                return new Response<IEnumerable<contractor_employee>>
                {
                    Success = false,
                    Message = "Error retrieving contractors"
                };
            }
        }

        public async Task<Response<int>> GetActiveCount()
        {
            try
            {
                var count = await _contractorRepository.GetActiveCount();
                return new Response<int>
                {
                    Success = true,
                    Message = "Active contractors count retrieved successfully",
                    Data = count
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting active contractors count");
                return new Response<int>
                {
                    Success = false,
                    Message = "Error retrieving active contractors count",
                    Data = 0
                };
            }
        }

        /// <summary>
        /// Bulk-import contractors for a single provider/project from a parsed file.
        /// Provider/project are validated once (and must belong together); each row is
        /// then inserted via Create() so it reuses the same field + DOLE 18+ validation
        /// and the {project_code}-NNNN auto employee_id generation. Valid rows insert;
        /// invalid rows are collected with row number + reason. One audit_log batch row
        /// is written regardless of partial failures.
        /// </summary>
        public async Task<Response<bulk_enrollment_result>> BulkCreate(bulk_enrollment_request request, string admin_employee_id)
        {
            var result = new bulk_enrollment_result
            {
                provider_code = request?.provider_code,
                project_code = request?.project_code,
                file_name = request?.file_name
            };

            try
            {
                if (request == null || request.contractors == null || request.contractors.Count == 0)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "No contractor rows were provided for import.",
                        Data = result
                    };
                }

                result.total = request.contractors.Count;

                // Fail fast: the modal's provider/project must be valid and belong together.
                if (string.IsNullOrWhiteSpace(request.provider_code) || string.IsNullOrWhiteSpace(request.project_code))
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Provider and Project are required.",
                        Data = result
                    };
                }

                var project = await _projectRepository.GetByProjectCode(request.project_code);
                if (project == null)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Selected project was not found.",
                        Data = result
                    };
                }

                if (!string.Equals(project.provider_code, request.provider_code, StringComparison.OrdinalIgnoreCase))
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "The selected project does not belong to the selected provider.",
                        Data = result
                    };
                }

                var provider = await _providerRepository.GetByProviderCode(request.provider_code);
                if (provider == null)
                {
                    return new Response<bulk_enrollment_result>
                    {
                        Success = false,
                        Message = "Selected provider was not found.",
                        Data = result
                    };
                }

                // Insert each row. Create() enforces required fields, DOLE 18+ birthdate,
                // and provider/project existence; gender is checked here because Create()
                // does not validate it.
                foreach (var row in request.contractors)
                {
                    var normalizedGender = (row.gender ?? string.Empty).Trim();
                    if (!string.Equals(normalizedGender, "Male", StringComparison.OrdinalIgnoreCase) &&
                        !string.Equals(normalizedGender, "Female", StringComparison.OrdinalIgnoreCase))
                    {
                        result.error_count++;
                        result.errors.Add(new bulk_enrollment_error
                        {
                            row = row.row_number,
                            name = row.name,
                            message = "Gender must be Male or Female."
                        });
                        continue;
                    }

                    var employee = new contractor_employee
                    {
                        name = row.name,
                        gender = normalizedGender,
                        birthdate = row.birthdate,
                        contact_number = row.contact_number,
                        address = row.address,
                        area_of_destination = row.area_of_destination,
                        position = row.position,
                        provider_code = request.provider_code,
                        project_code = request.project_code,
                        active = 1
                    };

                    var created = await Create(employee);
                    if (created.Success && created.Data != null)
                    {
                        result.success_count++;
                        result.enrolled_employee_ids.Add(created.Data.employee_id);
                    }
                    else
                    {
                        result.error_count++;
                        result.errors.Add(new bulk_enrollment_error
                        {
                            row = row.row_number,
                            name = row.name,
                            message = created.Message ?? "Could not enroll this contractor."
                        });
                    }
                }

                // Record the batch in the reusable audit log (best-effort: never fail the
                // import if logging itself fails).
                var logResponse = await _auditLogService.Log(
                    "bulk_enrollment",
                    "bulk_create",
                    request.project_code,
                    null,
                    result,
                    admin_employee_id);

                if (logResponse.Success && logResponse.Data != null)
                {
                    result.log_id = logResponse.Data.log_id;
                }

                _logger.LogInformation(
                    "Bulk enrollment complete: {Success} succeeded, {Errors} failed (project {ProjectCode}, admin {Admin})",
                    result.success_count, result.error_count, request.project_code, admin_employee_id);

                return new Response<bulk_enrollment_result>
                {
                    Success = true,
                    Message = $"Enrolled {result.success_count} of {result.total} contractor(s); {result.error_count} failed.",
                    Data = result
                };
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error during bulk enrollment (project {ProjectCode})", request?.project_code);
                return new Response<bulk_enrollment_result>
                {
                    Success = false,
                    Message = "An error occurred during bulk enrollment.",
                    Data = result
                };
            }
        }
    }
}